
(function(){
"use strict";
var KEY="kadala_hotel_oct_2026_live_v2";
var EXP=[["staff","Staff Salary"],["rent","Rent"],["egg","Egg"],["fish","Fish"],["chicken","Chicken"],["water","Water"],["gas","Gas"],["vegetables","Vegetables"],["cooldrinks","Cool Drinks"],["chapati","Chapati"],["dairy","Dairy"],["misc","Miscellaneous"],["extra","Extra"],["leaf","Leaf Meal Plates"]];
var FIELDS=["upi","cash"].concat(EXP.map(function(x){return x[0];})).concat(["notes"]);
var selectedMonth=today().slice(0,7);
var state=ensure({});var saveTimer=null;var sessionInfo=null;var pending=new Set();var saving=null;var formDirty=false;var formRevision=0;
function e(id){return document.getElementById(id)}function n(v){v=Number(v||0);return isFinite(v)?v:0}function money(v){try{return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n(v))}catch(err){return "₹"+Math.round(n(v))}}function percent(v){return (Math.round(v*10)/10).toFixed(1).replace(".0","")+"%"}
function today(){var d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function validMonth(m){return /^\d{4}-(0[1-9]|1[0-2])$/.test(m)&&Number(m.slice(0,4))>=1000}
function dates(month){month=month||selectedMonth;var p=month.split("-"),count=new Date(Number(p[0]),Number(p[1]),0).getDate(),a=[];for(var d=1;d<=count;d++)a.push(month+"-"+String(d).padStart(2,"0"));return a}
function validDate(d){return typeof d==="string"&&validMonth(d.slice(0,7))&&dates(d.slice(0,7)).indexOf(d)!==-1}
function defaultDate(){return today().slice(0,7)===selectedMonth?today():selectedMonth+"-01"}
function monthLabel(){return dObj(selectedMonth+"-01").toLocaleDateString("en-IN",{month:"long",year:"numeric"})}
function refreshMonth(){e("monthPicker").value=selectedMonth;e("monthBadge").textContent=monthLabel();e("billingMonth").textContent=monthLabel();e("clearMonthBtn").textContent="Clear "+monthLabel()}
function changeMonth(m){if(formDirty&&!confirm("Discard unsaved Daily Entry changes?")){e("monthPicker").value=selectedMonth;return}if(!validMonth(m)){e("monthPicker").value=selectedMonth;return}selectedMonth=m;state=ensure(state);refreshMonth();renderLedger();renderDashboard();loadForm(defaultDate())}
function moveMonth(offset){var d=dObj(selectedMonth+"-01");d.setMonth(d.getMonth()+offset);changeMonth(String(d.getFullYear()).padStart(4,"0")+"-"+String(d.getMonth()+1).padStart(2,"0"))}
function clearSelectedMonth(){}
function record(d){return {date:d,upi:0,cash:0,staff:0,rent:0,egg:0,fish:0,chicken:0,gas:0,vegetables:0,cooldrinks:0,chapati:0,dairy:0,misc:0,extra:0,leaf:0,water:0,customExpenses:[],notes:""}}
function ensure(x){if(!x||typeof x!=="object"||Array.isArray(x))x={};Object.keys(x).forEach(function(d){if(!validDate(d))delete x[d]});Object.keys(x).concat(dates()).forEach(function(d){if(!x[d]||typeof x[d]!=="object")x[d]=record(d);x[d].water=n(x[d].water);x[d].customExpenses=normalizeCustom(x[d].customExpenses)});return x}
async function api(path,method,body){var response=await fetch(path,{method:method||"GET",headers:{"Content-Type":"application/json","X-CSRF-Token":sessionInfo?sessionInfo.csrf:""},body:body?JSON.stringify(body):undefined});var data=await response.json();if(!response.ok){var err=new Error(data.error||"Unable to save.");err.status=response.status;throw err}return data}
function status(text,error){e("syncMessage").textContent=text;e("syncMessage").className=error?"red":"green";e("saveStatus").textContent=error?"Not saved":"Saved";e("retryBtn").hidden=!pending.size;e("draftBtn").hidden=!pending.size}
async function save(){if(saving)return saving;saving=(async function(){while(pending.size){var d=pending.values().next().value,snapshot=JSON.parse(JSON.stringify(state[d])),expected=snapshot._revision||0;try{var result=await api("/api/records/"+d,"PUT",{record:snapshot,revision:expected});var unchanged=JSON.stringify(state[d])===JSON.stringify(snapshot);state[d]._revision=result.revision;if(unchanged)pending.delete(d);if(e("date").value===d&&!formDirty)formRevision=result.revision;status(pending.size?"Saving…":"Saved for everyone",false)}catch(err){status(err.message+(err.status===401?" Open Sign in in a new tab, then retry.":""),true);if(err.status===409){e("retryBtn").hidden=true}throw err}}})().finally(function(){saving=null});return saving}
function queue(d){pending.add(d);e("saveStatus").textContent="Saving…";clearTimeout(saveTimer);saveTimer=setTimeout(function(){save().catch(function(){})},500)}
async function refreshRecords(){if(pending.size){try{await save()}catch(err){if(err.status!==409)throw err;if(!confirm("Another person changed a day you edited. Download your unsaved changes and load the latest shared records?"))return;var draft={};pending.forEach(function(d){draft[d]=state[d]});download(JSON.stringify(draft,null,2),"Kadala_Unsaved_Changes.json","application/json");pending.clear();formDirty=false}}if(formDirty&&!confirm("Discard the unsaved Daily Entry form and load the latest shared records?"))return;var data=await api("/api/records");state=ensure(data.records);renderLedger();renderDashboard();loadForm(e("date").value||defaultDate());status("Shared records refreshed",false)}
function bill(r){return n(r.upi)+n(r.cash)}function meatTotal(r){return n(r.egg)+n(r.fish)+n(r.chicken)}function expense(r){var t=0;EXP.forEach(function(x){t+=n(r[x[0]])});return t+customTotal(r.customExpenses)}function prof(r){return bill(r)-expense(r)}function margin(r){var b=bill(r);return b?prof(r)/b*100:0}
function has(r){if(normalizeCustom(r.customExpenses).some(function(x){return x.name.trim()||x.amount}))return true;if(String(r.notes||"").trim())return true;return FIELDS.filter(function(k){return k!="notes"}).some(function(k){return n(r[k])!==0})}
function dObj(s){var p=s.split("-");return new Date(Number(p[0]),Number(p[1])-1,Number(p[2]))}function dLabel(s){return dObj(s).toLocaleDateString("en-IN",{day:"2-digit",month:"short"})}function dow(s){return dObj(s).toLocaleDateString("en-IN",{weekday:"short"})}
function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function show(name){document.querySelectorAll(".page").forEach(function(p){p.classList.remove("active")});document.querySelectorAll(".tab").forEach(function(b){b.classList.remove("active")});e(name).classList.add("active");document.querySelector('.tab[data-page="'+name+'"]').classList.add("active");if(name==="dashboard")renderDashboard()}
function input(date,key,cls){var r=state[date],val=key==="notes"?(r[key]||""):(n(r[key])||"");if(key==="notes")return '<input class="cell noteinput '+(cls||"")+'" data-date="'+date+'" data-key="'+key+'" type="text" value="'+esc(val)+'" placeholder="Optional">';return '<input class="cell '+(cls||"")+'" data-date="'+date+'" data-key="'+key+'" type="number" min="0" step="0.01" inputmode="decimal" value="'+val+'" placeholder="0">'}
function renderLedger(){var h="";dates().forEach(function(d){var r=state[d],p=prof(r);h+='<tr data-row="'+d+'"><td class="sticky datecell">'+dLabel(d)+'<small>'+dow(d)+'</small></td><td>'+input(d,"upi")+'</td><td>'+input(d,"cash")+'</td><td class="calc" data-calc="'+d+'-bill">'+money(bill(r))+'</td><td>'+input(d,"staff")+'</td><td>'+input(d,"rent")+'</td><td class="meatcell">'+input(d,"egg")+'</td><td class="meatcell">'+input(d,"fish")+'</td><td class="meatcell">'+input(d,"chicken")+'</td><td class="calc meatcell" data-calc="'+d+'-meat">'+money(meatTotal(r))+'</td><td>'+input(d,"water")+'</td><td>'+input(d,"gas")+'</td><td>'+input(d,"vegetables")+'</td><td>'+input(d,"cooldrinks")+'</td><td>'+input(d,"chapati")+'</td><td>'+input(d,"dairy")+'</td><td>'+input(d,"misc")+'</td><td>'+input(d,"extra")+'</td><td>'+input(d,"leaf")+'</td><td><button class="secondary" data-custom-day="'+d+'">'+money(customTotal(r.customExpenses))+' · Edit</button></td><td class="calc" data-calc="'+d+'-exp">'+money(expense(r))+'</td><td class="calc profit '+(p>=0?"pos":"neg")+'" data-calc="'+d+'-profit">'+money(p)+'</td><td class="calc" data-calc="'+d+'-margin">'+percent(margin(r))+'</td><td>'+input(d,"notes")+'</td></tr>'});e("ledgerBody").innerHTML=h;document.querySelectorAll("[data-custom-day]").forEach(function(el){el.addEventListener("click",function(){loadForm(this.getAttribute("data-custom-day"));show("entry");e("addCustomExpense").focus()})});document.querySelectorAll("[data-date][data-key]").forEach(function(el){el.addEventListener("input",function(){var d=this.getAttribute("data-date"),k=this.getAttribute("data-key");state[d][k]=k==="notes"?this.value:n(this.value);updateRow(d);renderDashboard();queue(d)})})}
function setCalc(d,k,text,cls){var el=document.querySelector('[data-calc="'+d+'-'+k+'"]');if(el){el.textContent=text;if(cls)el.className=cls}}
function updateRow(d){var r=state[d],p=prof(r);setCalc(d,"bill",money(bill(r)));setCalc(d,"meat",money(meatTotal(r)));setCalc(d,"exp",money(expense(r)));setCalc(d,"profit",money(p),"calc profit "+(p>=0?"pos":"neg"));setCalc(d,"margin",percent(margin(r)))}
function totals(){var t={upi:0,cash:0,expense:0,profit:0,meat:0,days:0,cats:{}};EXP.forEach(function(x){t.cats[x[0]]=0});dates().forEach(function(d){var r=state[d];t.upi+=n(r.upi);t.cash+=n(r.cash);t.expense+=expense(r);t.profit+=prof(r);t.meat+=meatTotal(r);EXP.forEach(function(x){t.cats[x[0]]+=n(r[x[0]])});if(has(r))t.days++});return t}
function renderDashboard(){var t=totals(),total=t.upi+t.cash,m=total?t.profit/total*100:0,avg=t.days?total/t.days:0,us=total?t.upi/total*100:0,cs=total?t.cash/total*100:0;e("mBilling").textContent=money(total);e("mUpi").textContent=money(t.upi);e("mCash").textContent=money(t.cash);e("mExpense").textContent=money(t.expense);e("mProfit").textContent=money(t.profit);e("mProfit").className=t.profit>=0?"green":"red";e("mMargin").textContent=percent(m);e("mMargin").className=m>=0?"green":"red";e("mMeat").textContent=money(t.meat);e("mAvg").textContent=money(avg);e("daysEntered").textContent=t.days+" day"+(t.days===1?"":"s")+" entered";e("upiShare").textContent=percent(us)+" of billing";e("cashShare").textContent=percent(cs)+" of billing";e("upiBar").style.width=us+"%";e("cashBar").style.width=cs+"%";e("legendUpi").textContent=money(t.upi);e("legendCash").textContent=money(t.cash);e("splitLabel").innerHTML=total?"<b>UPI "+percent(us)+" • Cash / Delivery "+percent(cs)+"</b>":"<b>No billing entered yet</b>";
var customCats=new Map();dates().forEach(function(d){normalizeCustom(state[d].customExpenses).forEach(function(x){var label=x.name||"Other";customCats.set(label,(customCats.get(label)||0)+x.amount)})});var categories=EXP.map(function(x){return [x[1],t.cats[x[0]]]});customCats.forEach(function(value,label){categories.push(["Other: "+label,value])});
var mx=Math.max.apply(null,[1].concat(categories.map(function(x){return x[1]})));e("breakdown").innerHTML=categories.map(function(x){var v=x[1];return '<div class="barrow"><div>'+esc(x[0])+'</div><div class="track"><div class="bar" style="width:'+((v/mx)*100)+'%"></div></div><div class="right">'+money(v)+'</div></div>'}).join("");
var rows=dates().filter(function(d){return has(state[d])}).sort().reverse();e("dailyPerformance").innerHTML=rows.length?rows.map(function(d){var r=state[d],p=prof(r);return '<div class="record"><div class="date">'+dLabel(d)+'<small>'+dow(d)+'</small></div><div class="info"><b>'+money(bill(r))+'</b><span>Expenses '+money(expense(r))+'</span></div><div class="profit '+(p>=0?"green":"red")+'">'+money(p)+'</div></div>'}).join(""):'<div class="empty">Enter values in Daily Entry or Editable Ledger.</div>'}
function live(){var b=n(e("upi").value)+n(e("cash").value),ex=0;EXP.forEach(function(x){ex+=n(e(x[0]).value)});ex+=customTotal(readCustomForm());var mt=n(e("egg").value)+n(e("fish").value)+n(e("chicken").value),p=b-ex;e("meat").value=money(mt);e("liveBilling").textContent=money(b);e("liveExpense").textContent=money(ex);e("liveProfit").textContent=money(p);e("liveProfit").className=p>=0?"green":"red"}
function clearForm(keep){formDirty=false;var d=e("date").value;["upi","cash"].concat(EXP.map(function(x){return x[0]})).forEach(function(k){e(k).value=""});e("notes").value="";renderCustomForm([]);e("date").value=keep?(d||defaultDate()):defaultDate();e("editLabel").textContent="New record";live()}
function loadForm(d){clearForm(false);formRevision=state[d]?state[d]._revision||0:0;e("date").value=d;e("date").dataset.loadedDate=d;var r=state[d];if(r){["upi","cash"].concat(EXP.map(function(x){return x[0]})).forEach(function(k){e(k).value=n(r[k])||""});e("notes").value=r.notes||"";renderCustomForm(r.customExpenses);e("editLabel").textContent="Editing "+dLabel(d)}live()}
async function saveForm(){var d=e("date").value;if(!validDate(d)){alert("Choose a valid date.");return}var custom=readCustomForm();if(custom.some(function(x){return !x.name.trim()||!Number.isFinite(x.amount)||x.amount<0})){alert("Enter a name and a valid non-negative price for each custom expense.");return}if(!e("water").checkValidity()){e("water").reportValidity();return}if(pending.has(d)){try{await save()}catch(err){return}}var r=Object.assign({},state[d]||record(d));r._revision=formRevision;r.customExpenses=custom;r.date=d;r.upi=n(e("upi").value);r.cash=n(e("cash").value);EXP.forEach(function(x){r[x[0]]=n(e(x[0]).value)});r.notes=e("notes").value||"";state[d]=r;selectedMonth=d.slice(0,7);state=ensure(state);refreshMonth();pending.add(d);e("saveBtn").disabled=true;try{await save();formDirty=false;formRevision=state[d]._revision;renderLedger();renderDashboard();show("dashboard")}catch(err){alert(err.message)}finally{e("saveBtn").disabled=false}}
function download(content,name,type){var a=document.createElement("a"),u=URL.createObjectURL(new Blob([content],{type:type}));a.href=u;a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(u);a.remove()},150)}
function exportCsv(){var h=["Date","UPI","Cash / Delivery","Total Billing"].concat(EXP.map(function(x){return x[1]})).concat(["Custom Expenses","Custom Expenses Total","Meat Total","Total Expenses","Net Profit","Margin %","Notes"]),lines=[h.join(",")];dates().forEach(function(d){var r=state[d],v=[d,r.upi||0,r.cash||0,bill(r)].concat(EXP.map(function(x){return r[x[0]]||0})).concat(['"'+normalizeCustom(r.customExpenses).map(function(x){return x.name+": "+x.amount}).join("; ").replace(/"/g,'""')+'"',customTotal(r.customExpenses),meatTotal(r),expense(r),prof(r),margin(r),'"'+String(r.notes||"").replace(/"/g,'""')+'"']);lines.push(v.join(","))});download(lines.join("\n"),"Kadala_"+selectedMonth+".csv","text/csv")}
async function restore(file){try{if(pending.size||formDirty)throw Error("Save current changes before importing.");var records=JSON.parse(await file.text());if(!records||typeof records!=="object"||Array.isArray(records))throw Error("Invalid backup.");Object.keys(records).forEach(function(d){if(!has(records[d]))delete records[d]});if(!confirm("Import "+Object.keys(records).length+" days into the shared database? Existing shared dates will be kept."))return;var result=await api("/api/import","POST",{records:records});await refreshRecords();alert(result.imported+" days imported; "+result.skipped+" existing days kept.")}catch(err){alert(err.message)}finally{e("restoreFile").value=""}}
function normalizeCustom(items){return Array.isArray(items)?items.filter(function(x){return x&&typeof x==="object"}).map(function(x){return {name:String(x.name||""),amount:Math.max(0,n(x.amount))}}):[]}
function customTotal(items){return normalizeCustom(items).reduce(function(t,x){return t+x.amount},0)}
function readCustomForm(){return Array.from(e("customExpenses").children).map(function(row){var price=row.querySelector('[data-custom="amount"]');return {name:row.querySelector('[data-custom="name"]').value.trim(),amount:price.validity.badInput?NaN:Number(price.value||0)}})}
function renderCustomForm(items){e("customExpenses").innerHTML="";normalizeCustom(items).forEach(addCustomRow)}
function addCustomRow(item){item=item||{name:"",amount:0};var row=document.createElement("div");row.className="customExpense";row.innerHTML='<div><label>Expense name<input data-custom="name" type="text" maxlength="100" placeholder="e.g. Cleaning supplies" aria-label="Custom expense name" value="'+esc(item.name)+'"></label></div><div><label>Price (₹)<input data-custom="amount" type="number" min="0" step="0.01" inputmode="decimal" aria-label="Custom expense price" placeholder="0" value="'+(item.amount||"")+'"></label></div><button type="button" aria-label="Remove custom expense">Remove</button>';row.addEventListener("input",live);row.querySelector("button").addEventListener("click",function(){row.remove();live()});e("customExpenses").appendChild(row)}
e("addCustomExpense").addEventListener("click",function(){addCustomRow();e("customExpenses").lastElementChild.querySelector("input").focus();live()});
document.querySelectorAll(".tab").forEach(function(b){b.addEventListener("click",function(){show(this.getAttribute("data-page"))})});["upi","cash"].concat(EXP.map(function(x){return x[0]})).forEach(function(k){e(k).addEventListener("input",live)});e("date").addEventListener("change",function(){if(formDirty&&!confirm("Discard unsaved Daily Entry changes?")){this.value=e("date").dataset.loadedDate;return}if(validDate(this.value)){selectedMonth=this.value.slice(0,7);state=ensure(state);refreshMonth();renderLedger();renderDashboard();loadForm(this.value)}});e("saveBtn").addEventListener("click",saveForm);e("clearFormBtn").addEventListener("click",function(){clearForm(true)});e("exportBtn").addEventListener("click",exportCsv);e("backupBtn").addEventListener("click",function(){download(JSON.stringify(state,null,2),"Kadala_All_Months_Backup.json","application/json")});e("restoreBtn").addEventListener("click",function(){e("restoreFile").click()});e("restoreFile").addEventListener("change",function(){if(this.files&&this.files[0])restore(this.files[0])});e("clearMonthBtn").addEventListener("click",function(){if(confirm("Clear all data for "+monthLabel()+"? Other months will be kept.")){clearSelectedMonth()}});e("monthPicker").addEventListener("change",function(){changeMonth(this.value)});e("prevMonth").addEventListener("click",function(){moveMonth(-1)});e("nextMonth").addEventListener("click",function(){moveMonth(1)});e("todayBtn").addEventListener("click",function(){changeMonth(today().slice(0,7));loadForm(today())});e("entry").addEventListener("input",function(event){if(event.target.id!=="date")formDirty=true});e("entry").addEventListener("click",function(event){if(event.target.id==="addCustomExpense"||event.target.closest(".customExpense button"))formDirty=true});
e("logoutBtn").addEventListener("click",async function(){if(pending.size){try{await save()}catch(err){return}}if(formDirty&&!confirm("Sign out and discard unsaved form changes?"))return;try{await api("/api/logout","POST",{});location.replace("/login")}catch(err){status(err.message,true)}});
e("refreshBtn").addEventListener("click",function(){refreshRecords().catch(function(err){status(err.message,true)})});
e("retryBtn").addEventListener("click",async function(){try{sessionInfo=await api("/api/session");await save()}catch(err){status(err.message,true)}});
e("draftBtn").addEventListener("click",function(){var draft={};pending.forEach(function(d){draft[d]=state[d]});download(JSON.stringify(draft,null,2),"Kadala_Unsaved_Changes.json","application/json")});
window.addEventListener("beforeunload",function(event){if(pending.size||formDirty){event.preventDefault();event.returnValue=""}});
(async function(){try{sessionInfo=await api("/api/session");var data=await api("/api/records");state=ensure(data.records);e("accountLabel").textContent=sessionInfo.username+" · "+sessionInfo.role;e("accountsLink").hidden=sessionInfo.role!=="owner";e("restoreBtn").hidden=sessionInfo.role!=="owner";refreshMonth();renderLedger();renderDashboard();loadForm(today());e("startup").hidden=true;e("sharedApp").hidden=false;status("Shared records loaded",false)}catch(err){e("startup").firstChild.textContent=err.message+" ";}})()
})();
