(()=>{'use strict';const el=id=>document.getElementById(id);let session,revision=0,loadedDay='',dirty=false,busy=false;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function message(text,error=false){el('message').textContent=text;el('message').className=error?'error':'success';}
async function api(path,method='GET',body){const response=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':session?.csrf||''},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed.');return data;}
function lock(value){busy=value;el('inventoryForm').querySelectorAll('input,select,button').forEach(node=>node.disabled=value);}
function row(item,custom){const node=document.createElement('div');node.className='stock-row';if(custom){const label=document.createElement('label');label.textContent='Item name';const input=document.createElement('input');input.dataset.field='name';input.value=item.name;input.required=true;input.maxLength=100;label.append(input);node.append(label);}else{const title=document.createElement('div');title.className='item';title.textContent=item.name;node.dataset.name=item.name;node.append(title);}
const unitLabel=document.createElement('label');unitLabel.className='unit';unitLabel.textContent='Unit';const unit=document.createElement('select');unit.dataset.field='unit';for(const value of ['kg','g','litres','ml','pieces']){const option=document.createElement('option');option.value=value;option.textContent=value;unit.append(option)}unit.value=item.unit;unitLabel.append(unit);node.append(unitLabel);
for(const key of ['opening','closing']){const label=document.createElement('label');label.textContent=key==='opening'?'Opening stock':'Closing stock';const input=document.createElement('input');input.type='number';input.min='0';input.max='1000000000';input.step='0.001';input.inputMode='decimal';input.placeholder='Not counted';input.dataset.field=key;input.value=item[key]??'';label.append(input);node.append(label)}
if(custom){const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.onclick=()=>{node.remove();dirty=true};node.append(remove)}return node;}
function render(record){el('meatRows').replaceChildren();el('customRows').replaceChildren();for(const item of record.meat)el('meatRows').append(row(item,false));for(const item of record.custom)el('customRows').append(row(item,true));}
function read(){const rows=id=>Array.from(el(id).children).map(node=>({name:node.dataset.name||node.querySelector('[data-field="name"]').value.trim(),unit:node.querySelector('[data-field="unit"]').value,...Object.fromEntries(['opening','closing'].map(key=>{const value=node.querySelector(`[data-field="${key}"]`).value;return [key,value===''?null:Number(value)]}))}));return {date:loadedDay,meat:rows('meatRows'),custom:rows('customRows')};}
async function load(day){if(busy)return;if(dirty&&!confirm('Discard unsaved inventory changes? Download a copy first if you need to keep them.')){el('stockDate').value=loadedDay;return}lock(true);try{const data=await api('/api/inventory/'+day);loadedDay=day;revision=data.revision;render(data.record||{meat:[{name:'Chicken',unit:'kg'},{name:'Fish',unit:'kg'},{name:'Egg',unit:'pieces'}],custom:[]});el('stockDate').value=day;dirty=false;message(data.record?'Saved inventory loaded.':'No stock recorded for this date yet.');}catch(err){el('stockDate').value=loadedDay;message(err.message,true)}finally{lock(false)}}
el('inventoryForm').oninput=event=>{if(event.target.id!=='stockDate')dirty=true};el('stockDate').onchange=()=>load(el('stockDate').value);el('stockToday').onclick=()=>load(today());el('reloadStock').onclick=()=>load(loadedDay);
el('addStock').onclick=()=>{if(el('customRows').children.length>=100){message('Use at most 100 custom items.',true);return}const item=row({name:'',unit:'kg'},true);el('customRows').append(item);item.querySelector('input').focus();dirty=true};
el('inventoryForm').onsubmit=async event=>{event.preventDefault();if(busy||!loadedDay)return;const record=read();lock(true);try{const result=await api('/api/inventory/'+loadedDay,'PUT',{record,revision});revision=result.revision;dirty=false;message('Inventory saved for everyone.')}catch(err){message(err.message,true)}finally{lock(false)}};
el('downloadStock').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(read(),null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`Kadala_Inventory_${loadedDay}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
el('signout').onclick=async()=>{if(dirty&&!confirm('Discard unsaved inventory and sign out?'))return;try{await api('/api/logout','POST',{});dirty=false;location.replace('/login')}catch(err){message(err.message,true)}};
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue=''}});
(async()=>{try{session=await api('/api/session');el('account').textContent=`${session.username} · ${session.role==='inventory'?'Inventory only':session.role}`;el('dashboardLink').hidden=session.role==='inventory';el('manageLink').hidden=session.role!=='owner';el('inventoryForm').hidden=false;await load(today())}catch(err){message(err.message,true)}})();})();
